@startuml
!include plantuml-ae-style.iuml


skinparam  Note {
     BackgroundColor white
     BorderColor white
     FontStyle         normal
     TextAlignment  left
}


title
  <b>shf:db_prep sequence   RAILS_ENV = test </b>

 - no schema.rb (deleted before running the task)
 - no structure.rb (deleted before running the task)

end title

start
-[#magenta]->

floating note right

 magenta arrows = the path taken originally (uses schema.rb)

 blue arrows = the path <b>after</b> I added ""config.active_record.schema_format = :sql""
     into <b>""config/environments/test.rb""</b>

     (""config/environments/development"" already has ""config.active_record.schema_format = :sql"")

end note

#lightgreen:shf db_prep;
note left #lightgreen
  green = shf task
end note

-[#blue]->
#lightcyan:db:drop;
note right #lightcyan
 light cyan = in
 <i>activerecord-5.2.3/lib/active_record/railties/databases.rake</i>
end note
-[#blue]->

#lightcyan:db:create;
-[#blue]->
#lightcyan:db:migrate;
-[#blue]->
#lightcyan:db:_dump;
 -[#blue]->
if (ActiveRecord::Base.dump_schema_after_migration) then (yes)
   -[#magenta]->
  if (ActiveRecord::Base.schema_format == :ruby) then (yes)
    -[#magenta]->
    #lightcyan:db_namespace["schema:dump"].invoke;
    -[#magenta]->
    :ActiveRecord::SchemaDumper.dump;
    -[#magenta]->
  elseif  (ActiveRecord::Base.schema_format == :sql) then (yes)
    -[#blue]->
    #lightcyan:db_namespace["structure:dump"].invoke;
    -[#blue]->
    :ActiveRecord::Tasks::DatabaseTasks.structure_dump;
  endif

  '-[#blue]->
else (no)

endif
 -[#blue]->
#lightcyan:db:test:prepare;
-[#blue]->
#lightcyan:db:test:load;
-[#blue]->

if (ActiveRecord::Base.schema_format == :ruby ?\n\n(ruby is the default)) then (yes)
  -[#magenta]->
  #lightcyan:db_namespace["test:load_schema"].invoke;
  -[#magenta]->
  :ActiveRecord::Tasks::DatabaseTasks.load_schema;
  note right
    white = in
    activerecord-5.2.3/lib/active_record/tasks/database_tasks.rb
  end note
  -[#magenta]->
  :check_schema_file(db/schema.rb);
  -[#magenta]->
  if (db/schema.rb file exists?) then (yes)
   -[#magenta]->
   if (format == :ruby) then (yes)
     -[#magenta]->
     :load(file);
     -[#magenta]->
   elseif (format == :sql) then (yes)
     :structure_load(configuration, file);
   endif
   -[#magenta]->

  else (no)

    stop
  endif

elseif (ActiveRecord::Base.schema_format == :sql ?) then (yes)
  -[#blue]->
  #lightcyan::db_namespace["test:load_structure"].invoke;
  -[#blue]->
  :ActiveRecord::Tasks::DatabaseTasks.load_schema;
  
  :check_schema_file(db/structure.sql);
  -[#blue]->

  if (db/structure.sql file exists?) then (yes)
   -[#blue]->
   if (format == :ruby) then (yes)
     :load(file);
   elseif (format == :sql) then (yes)
      -[#blue]->
     :structure_load(configuration, file);
     -[#blue]->
   endif

  -[#blue]->
  else (no)
    stop
  endif
endif


#lightgreen:shf load_regions;
-[#blue]->
#lightgreen:shf load_kommuns;
-[#blue]->
#lightgreen:shf load_file_delivery_methods;

-[#blue]->
stop


@enduml
