HIPS_ORDERS_URL = ENV['SHF_HIPS_URL'] + 'orders/'

HIPS_JS_CDN     = ENV['SHF_HIPS_JS_CDN']

HIPS_PRIVATE_KEY = ENV['SHF_HIPS_PRIVATE_KEY']

HIPS_PUBLIC_KEY  = ENV['SHF_HIPS_PUBLIC_KEY']

SHF_MEMBER_FEE   = 30000  # unit == one hundredth of krona
SHF_BRANDING_FEE = 25000

HIPS_LOG = 'log/HIPS.log'

SHF_WEBHOOK_HOST = ENV['SHF_DEV_WEBHOOK_HOST']

public_key = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu269xcyVkOZLP93D82g8" \
"vsLgLMDIfc853syoQ6gu0K3kwMcSru9iNhj4CWEWp4t7ozDd3o+t6Y6scZtLnSrM" \
"ZhoUkdiOIK7hqF6e9tS+vT8vFOkrmsGysQJbY2IBaX4WknOsQEjARw04S37g6XUB" \
"ERXlC0VwUXrUZVsNCYrE0sa0OvZ/IxHLJrt+fpTOUFrcYowe6Ha7sZEz2ju1x8nq" \
"foEnsfVLRMsgVE+Af2uhANqSONCly0WWJID+q0gIqnDYQ/ETclGDeDcMU7J9/fUG" \
"euPoQtNRJKRWG/J0sqEWFjPtahDyq9slO5qn55rcYdOR2ZGHTkqvLVFwSOSivCmT" \
"1QIDAQAB"

HIPS_RSA_KEY = OpenSSL::PKey::RSA.new(Base64.decode64(public_key))

# Styling items for HIP checkout form
HIPS_FORM_MAIN_COLOR = '5692CE'
HIPS_FORM_SECONDARY_COLOR = '003A78'
HIPS_FORM_FONT = 'Comic Sans MS'
